DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS meal_has;
DROP TABLE IF EXISTS meal;
DROP TABLE IF EXISTS fooditem;

CREATE TABLE person(
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE
);

CREATE TABLE email(
  mail text PRIMARY KEY
);

CREATE TABLE meal(
  meal_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  user_id integer,
  date timestamp,
  FOREIGN KEY (user_id) REFERENCES person(user_id)
);

CREATE TABLE fooditem(
  item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text, 
  calories integer,
  protein integer,
  fat integer,
  carbs integer,
  fiber integer,
  sodium integer,
  cholesterol integer,
  vitamin_a integer,
  vitamin_b integer,
  vitamin_c integer,
  vitamin_d integer,
  vitamin_e integer,
  vitamin_k integer,
  zinc integer,
  potassium integer,
  magnesium integer,
  calcium integer,
  iron integer,
  selenium integer
);

CREATE TABLE meal_has(
  meal_id integer,
  food_id integer,
  amount integer DEFAULT 1,
  FOREIGN KEY (meal_id) REFERENCES meal(meal_id),
  FOREIGN KEY (food_id) REFERENCES fooditem(item_id),
  PRIMARY KEY (meal_id, food_id)
);

