DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS meal_has;
DROP TABLE IF EXISTS meal;
DROP TABLE IF EXISTS fooditem;

CREATE TABLE person(
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE
);

CREATE TABLE email(
  mail text PRIMARY KEY
);

CREATE TABLE meal(
  meal_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  user_id integer,
  date timestamp,
  FOREIGN KEY (user_id) REFERENCES person(user_id)
);

CREATE TABLE fooditem(
  item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text, 
  calories integer,
  protein integer,
  fat integer,
  carbs integer,
  fiber integer,
  sodium integer,
  cholesterol integer,
  vitamin_a integer,
  vitamin_b integer,
  vitamin_c integer,
  vitamin_d integer,
  vitamin_e integer,
  vitamin_k integer,
  zinc integer,
  potassium integer,
  magnesium integer,
  calcium integer,
  iron integer,
  selenium integer
);

CREATE TABLE meal_has(
  meal_id integer,
  food_id integer,
  amount integer DEFAULT 1,
  FOREIGN KEY (meal_id) REFERENCES meal(meal_id),
  FOREIGN KEY (food_id) REFERENCES fooditem(item_id),
  PRIMARY KEY (meal_id, food_id)
);

CREATE OR REPLACE FUNCTION get_month_schedule(user_name text, month integer)
RETURNS table(mealname text, date timestamp, fooditems text[]) AS
$$
  SELECT m.name, m.date, array_agg(f.name) fooditems FROM meal m
    INNER JOIN meal_has mh ON mh.meal_id = m.meal_id
    INNER JOIN fooditem f ON f.item_id = mh.food_id
  WHERE EXTRACT(MONTH FROM m.date) = month
  GROUP BY m.user_id, m.name, m.date
  HAVING m.user_id = (SELECT user_id FROM person p WHERE p.username = user_name)
$$ language sql;

CREATE OR REPLACE FUNCTION get_day_schedule(user_name text, day text)
RETURNS table(mealname text, date timestamp, fooditems text[]) AS
$$
  SELECT m.name, m.date, array_agg(f.name) fooditems FROM meal m
    INNER JOIN meal_has mh ON mh.meal_id = m.meal_id
    INNER JOIN fooditem f ON f.item_id = mh.food_id
  WHERE DATE(m.date) = day::date
  GROUP BY m.user_id, m.name, m.date
  HAVING m.user_id = (SELECT user_id FROM person p WHERE p.username = user_name)
$$ language sql;

